// Problem 2 - Even Fibonacci numbers
// https://projecteuler.net/problem=2
// Answer = 4613732

fn question() {
    println!("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.")
}


fn solve(bound: i32) -> i32{
    let mut sum = 0;
    let (mut a, mut b) = (1,2);
    while b < bound{
        if b % 2 == 0{
            sum = sum + b
        }
        (a, b) = (b, a+b);
    }
    sum
}



fn main() {
    question();
    println!("Answer = {}", solve(4000000));
}